# Generated by Django 4.2.7 on 2025-08-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
    ]
