# Generated by Django 4.2.7 on 2025-08-09 08:24

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0002_auto_20250809_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rakibul Hasan', max_length=100)),
                ('title', models.CharField(default='Ethical Hacker | Junior Penetration Tester | Programmer | Django Developer', max_length=200)),
                ('about', models.TextField(default='I am an ethical hacker and programmer with strong expertise in web application security, penetration testing, and backend development.')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('email', models.EmailField(default='rsrarakib1808@gmail.com', max_length=254)),
                ('location', models.CharField(default='Bogura, Bangladesh', max_length=100)),
                ('github_url', models.URLField(default='https://github.com/rshrakib')),
                ('linkedin_url', models.URLField(default='https://linkedin.com/in/rakibul-hasan/')),
                ('facebook_url', models.URLField(default='https://facebook.com/rshrakib')),
            ],
            options={
                'verbose_name': 'Profile Settings',
                'verbose_name_plural': 'Profile Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-featured', '-publish_date']},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-featured', '-created_date']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-level', 'name']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Brief description for blog listing', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=False, help_text='Feature on homepage'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.IntegerField(default=5, help_text='Estimated read time in minutes'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=10),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='certification',
            name='credential_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the certification'),
        ),
        migrations.AddField(
            model_name='certification',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='verification_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, help_text='Live demo URL', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('High', 'High Priority'), ('Medium', 'Medium Priority'), ('Low', 'Low Priority')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(blank=True, help_text='Technologies used (one per line)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(default='General', help_text='e.g., Programming, Cybersecurity, Tools', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Use the rich text editor for formatting'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=50, help_text='Skill level percentage (0-100)'),
        ),
    ]
