# Generated by Django 4.2.7 on 2025-08-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profile_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title or role', max_length=200)),
                ('company', models.CharField(help_text='Company or organization name', max_length=200)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=100)),
                ('experience_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('contract', 'Contract'), ('volunteer', 'Volunteer')], default='full_time', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of the experience')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if current)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Check if this is your current position')),
                ('description', models.TextField(help_text='Detailed description of your role and achievements')),
                ('technologies', models.TextField(blank=True, help_text='Technologies, tools, and skills used (one per line)')),
                ('achievements', models.TextField(blank=True, help_text='Key achievements and accomplishments (one per line)')),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo or image', null=True, upload_to='experience/')),
                ('company_website', models.URLField(blank=True, help_text='Company website URL', null=True)),
                ('featured', models.BooleanField(default=False, help_text='Feature this experience prominently')),
                ('priority', models.IntegerField(default=0, help_text='Display order (higher numbers appear first)')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-priority', '-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='pentester.rakib@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(default='https://www.facebook.com/HasanRakib.Dev'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.URLField(default='https://github.com/dev-rakibul-hasan'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(default='https://www.linkedin.com/in/dev-rakibul-hasan/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Rangpur, Bangladesh', max_length=100),
        ),
    ]
