# Generated by Django 4.2.7 on 2025-08-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_experience_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='About Me', help_text='Main title for the about page', max_length=200)),
                ('hero_subtitle', models.TextField(default='I am an ethical hacker, programmer, and developer passionate about building secure and scalable applications. I love learning new technologies and solving challenging problems that make a real impact.', help_text='Subtitle text below the main title')),
                ('journey_title', models.CharField(default='My Journey', help_text='Title for the journey section', max_length=200)),
                ('journey_content', models.TextField(default='I am Rakibul Hasan, a Computer Science and Engineering student at Begum Rokeya University, Rangpur (CSE-14). My journey began with programming, gradually expanding into ethical hacking, web security, and backend development.', help_text='Main journey description')),
                ('quick_facts_title', models.CharField(default='Quick Facts', help_text='Title for the quick facts section', max_length=200)),
                ('fact_1', models.CharField(default='Junior Penetration Tester Intern at Bytecapsule IT', help_text='First quick fact', max_length=200)),
                ('fact_2', models.CharField(default='CSE Student at Begum Rokeya University', help_text='Second quick fact', max_length=200)),
                ('fact_3', models.CharField(default='Django Developer & Security Specialist', help_text='Third quick fact', max_length=200)),
                ('fact_4', models.CharField(default='IoT Security Researcher', help_text='Fourth quick fact', max_length=200)),
                ('skills_title', models.CharField(default='Technical Skills', help_text='Title for the skills section', max_length=200)),
                ('experience_title', models.CharField(default='Experience', help_text='Title for the experience section', max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
    ]
