# Generated by Django 4.2.7 on 2025-08-10 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Profile this experience belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio.profile'),
        ),
    ]
