# Generated by Django 4.2.7 on 2025-08-11 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_experience_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='journey_content',
            field=models.TextField(default='I am a Computer Science and Engineering student passionate about ethical hacking, web security, and backend development.', help_text='Main journey description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(help_text='Profile this experience belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio.profile'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Language name', max_length=100)),
                ('proficiency', models.CharField(choices=[('native', 'Native'), ('fluent', 'Fluent'), ('professional', 'Professional Proficiency'), ('intermediate', 'Intermediate'), ('basic', 'Basic'), ('beginner', 'Beginner')], default='intermediate', help_text='Proficiency level', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about your language skills')),
                ('featured', models.BooleanField(default=False, help_text='Feature this language prominently')),
                ('priority', models.IntegerField(default=0, help_text='Display order (higher numbers appear first)')),
                ('profile', models.ForeignKey(help_text='Profile this language belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='Degree or qualification name', max_length=200)),
                ('institution', models.CharField(help_text='Institution or university name', max_length=200)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=100)),
                ('start_date', models.DateField(help_text='Start date')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if current)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Check if this is your current education')),
                ('description', models.TextField(blank=True, help_text='Additional details about your education')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text='GPA if applicable', max_digits=3, null=True)),
                ('achievements', models.TextField(blank=True, help_text='Notable achievements, awards, or activities')),
                ('degree_type', models.CharField(choices=[('bsc', 'BSc'), ('msc', 'MSc'), ('phd', 'PhD'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('other', 'Other')], default='bsc', help_text='Type of degree', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Feature this education prominently')),
                ('priority', models.IntegerField(default=0, help_text='Display order (higher numbers appear first)')),
                ('profile', models.ForeignKey(help_text='Profile this education belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='education', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-priority', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Achievement title', max_length=200)),
                ('description', models.TextField(help_text='Description of the achievement')),
                ('achievement_type', models.CharField(choices=[('award', 'Award'), ('competition', 'Competition'), ('certification', 'Certification'), ('publication', 'Publication'), ('presentation', 'Presentation'), ('project', 'Project'), ('other', 'Other')], default='award', help_text='Type of achievement', max_length=20)),
                ('organization', models.CharField(blank=True, help_text='Organization or institution', max_length=200)),
                ('date', models.DateField(help_text='Date of achievement')),
                ('certificate_image', models.ImageField(blank=True, help_text='Certificate or award image', null=True, upload_to='achievements/')),
                ('url', models.URLField(blank=True, help_text='Related URL or verification link', null=True)),
                ('featured', models.BooleanField(default=False, help_text='Feature this achievement prominently')),
                ('priority', models.IntegerField(default=0, help_text='Display order (higher numbers appear first)')),
                ('profile', models.ForeignKey(help_text='Profile this achievement belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-priority', '-date'],
            },
        ),
    ]
