# Generated by Django 4.2.7 on 2025-08-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_aboutpage_journey_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(default='+8801309598979', help_text='WhatsApp number with country code', max_length=20),
        ),
    ]
