# Generated by Django 4.2.7 on 2025-08-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_profile_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='+8801704 681848', help_text='Phone number with country code', max_length=20),
        ),
    ]
