# Generated by Django 4.2.7 on 2025-08-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secondary_email',
            field=models.EmailField(blank=True, default='pentester.rakib@outlook.com', help_text='Secondary email address', max_length=254),
        ),
    ]
