# Generated by Django 4.2.7 on 2025-08-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_profile_secondary_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='+8801309598979', help_text='Phone number with country code', max_length=20),
        ),
    ]
