# Generated by Django 4.2.7 on 2025-08-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='x_url',
            field=models.URLField(blank=True, default='https://x.com/PentesterRakib', help_text='X (Twitter) profile URL'),
        ),
    ]
