# Generated by Django 4.2.7 on 2025-08-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_profile_x_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Md. Rakibul Hasan', max_length=100),
        ),
    ]
